import { YOGSHALAPose } from "./types";

// Videos have been removed in favor of image-guided flows.
const DEFAULT_POSE_VIDEO = "";

export const YOGSHALA_POSES: YOGSHALAPose[] = [
  {
    id: "tadasana",
    name: "Mountain Pose",
    sanskritName: "Thadasana (Tadasana)",
    description: "A simple standing posture that builds balance, alignment, and body awareness.",
    benefits: ["Improves balance and posture", "Strengthens thighs, knees, and ankles", "Builds body awareness"],
    instructions: [
      "Stand with your big toes touching and heels slightly apart.",
      "Lift and spread your toes and the balls of your feet, then lay them softly back down.",
      "Engage your quadriceps to lift your kneecaps.",
      "Tuck your tailbone slightly and draw your belly in.",
      "Roll your shoulders back and down, letting your arms hang naturally.",
      "Gaze straight ahead and breathe deeply."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Inhale as you lengthen your spine, exhale as you ground your feet.",
    commonMistakes: ["Locking the knees", "Arching the lower back too much"],
    safetyTips: ["If you have low blood pressure, be careful when standing up."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "vrikshasana",
    name: "Tree Pose",
    sanskritName: "Vrikshasana",
    description: "A balancing pose that improves focus and strengthens the legs.",
    benefits: ["Improves balance", "Strengthens ankles and calves", "Tones abdominal muscles"],
    instructions: [
      "Start in Mountain Pose.",
      "Shift your weight to your left foot.",
      "Bend your right knee and place the sole of your right foot on your inner left thigh (avoid the knee).",
      "Bring your hands to prayer position at your chest.",
      "Find a steady point to gaze at.",
      "Hold for several breaths, then switch sides."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Focus on steady, rhythmic breathing to maintain balance.",
    commonMistakes: ["Placing the foot directly on the knee joint", "Hips not being level"],
    safetyTips: ["Use a wall for support if you're struggling with balance."],
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 45
  },
  {
    id: "balasana",
    name: "Child's Pose",
    sanskritName: "Balasana",
    description: "A resting pose that gently stretches the hips, thighs, and ankles.",
    benefits: ["Calms the brain", "Relieves stress and fatigue", "Stretches the back"],
    instructions: [
      "Kneel on the floor with your big toes touching.",
      "Sit on your heels, then separate your knees about as wide as your hips.",
      "Exhale and lay your torso down between your thighs.",
      "Lay your hands on the floor alongside your torso, palms up.",
      "Release the fronts of your shoulders toward the floor."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Breathe into the back of your torso, feeling it expand.",
    commonMistakes: ["Holding tension in the neck", "Knees too close together"],
    safetyTips: ["Place a pillow between your thighs and calves if you have knee pain."],
    imageUrl: "https://images.unsplash.com/photo-1510894347713-fc3ed6fdf539?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 60
  },
  {
    id: "marjaryasana",
    name: "Cat Pose",
    sanskritName: "Marjaryasana",
    description: "A gentle stretch for the back and neck that improves spinal flexibility.",
    benefits: ["Improves spinal flexibility", "Massages abdominal organs", "Relieves back pain"],
    instructions: [
      "Start on your hands and knees in a tabletop position.",
      "Exhale, draw your belly to your spine, and round your back toward the ceiling.",
      "Tuck your chin toward your chest.",
      "Keep your wrists directly under your shoulders."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Exhale as you round your back.",
    commonMistakes: ["Moving only the neck", "Not engaging the core"],
    safetyTips: ["Keep your wrists directly under your shoulders."],
    imageUrl: "https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "bitilasana",
    name: "Cow Pose",
    sanskritName: "Bitilasana",
    description: "A gentle backbend that warms up the spine and opens the chest.",
    benefits: ["Improves spinal flexibility", "Opens the chest", "Relieves stress"],
    instructions: [
      "Start on your hands and knees in a tabletop position.",
      "Inhale, drop your belly toward the mat, and look up.",
      "Lift your sit bones and chest toward the ceiling.",
      "Keep your shoulders away from your ears."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Inhale as you drop your belly.",
    commonMistakes: ["Collapsing into the shoulders", "Straining the neck"],
    safetyTips: ["Keep your wrists directly under your shoulders."],
    imageUrl: "https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "adho_mukha_svanasana",
    name: "Downward-Facing Dog",
    sanskritName: "Adho Mukha Svanasana",
    description: "One of the most widely recognized YOGSHALA poses, it stretches and strengthens the entire body.",
    benefits: ["Stretches shoulders, hamstrings, and calves", "Strengthens arms and legs", "Relieves stress"],
    instructions: [
      "Start on your hands and knees.",
      "Tuck your toes and lift your hips toward the ceiling.",
      "Push back through your hands to lengthen your spine.",
      "Keep your knees slightly bent if your hamstrings are tight.",
      "Let your head hang freely between your arms."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Deep, slow breaths through the nose.",
    commonMistakes: ["Rounding the back", "Putting too much weight on the wrists"],
    safetyTips: ["Spread your fingers wide to protect your wrists."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 60
  },
  {
    id: "bhujangasana",
    name: "Cobra Pose",
    sanskritName: "Bhujangasana",
    description: "A back-bending pose that strengthens the spine and stretches the chest.",
    benefits: ["Strengthens the spine", "Stretches chest and lungs", "Tones the buttocks"],
    instructions: [
      "Lie prone on the floor with your legs extended.",
      "Place your hands under your shoulders.",
      "Inhale and slowly lift your chest off the floor.",
      "Keep your elbows close to your body.",
      "Look slightly upward without straining your neck."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Inhale as you lift, exhale as you lower.",
    commonMistakes: ["Over-arching the lower back", "Shoulders creeping up to ears"],
    safetyTips: ["Avoid if you have a recent back injury or are pregnant."],
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800",
    duration: 30
  },
  {
    id: "setu_bandhasana",
    name: "Bridge Pose",
    sanskritName: "Setu Bandhasana",
    description: "A rejuvenating backbend that opens the chest and strengthens the legs.",
    benefits: ["Stretches the chest, neck, and spine", "Calms the brain", "Improves digestion"],
    instructions: [
      "Lie on your back with your knees bent and feet flat on the floor.",
      "Place your arms alongside your body, palms down.",
      "Exhale and press your feet and arms into the floor.",
      "Lift your hips toward the ceiling.",
      "Clasp your hands under your back and stay on your shoulders."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Deep abdominal breathing.",
    commonMistakes: ["Turning the head while in the pose", "Knees splaying outward"],
    safetyTips: ["Keep your neck neutral and do not move it from side to side."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 45
  },
  {
    id: "dandasana",
    name: "Staff Pose",
    sanskritName: "Dandasana",
    description: "A foundational seated pose that improves posture and strengthens the back.",
    benefits: ["Improves posture", "Strengthens back muscles", "Stretches shoulders and chest"],
    instructions: [
      "Sit on the floor with your legs extended straight in front of you.",
      "Flex your feet and engage your thigh muscles.",
      "Place your hands on the floor beside your hips.",
      "Lengthen your spine and lift through the crown of your head."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Inhale to lengthen the spine, exhale to ground the sit bones.",
    commonMistakes: ["Rounding the back", "Locking the knees"],
    safetyTips: ["Sit on a folded blanket if your lower back rounds."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "vajrasana",
    name: "Thunderbolt Pose",
    sanskritName: "Vajrasana",
    description: "A kneeling pose that improves digestion and calms the mind.",
    benefits: ["Improves digestion", "Calms the mind", "Strengthens pelvic muscles"],
    instructions: [
      "Kneel on the floor with your big toes touching.",
      "Sit back on your heels.",
      "Keep your spine straight and rest your hands on your thighs.",
      "Gaze forward and breathe deeply."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Slow, steady breathing.",
    commonMistakes: ["Arching the lower back", "Tension in the shoulders"],
    safetyTips: ["Place a cushion between your heels and sit bones if needed."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 60
  },
  {
    id: "savasana",
    name: "Corpse Pose",
    sanskritName: "Savasanam (Savasana)",
    description: "A relaxation pose practiced at the end of a session to rest the body and mind.",
    benefits: ["Encourages deep relaxation", "Relieves stress", "Releases full-body tension"],
    instructions: [
      "Lie flat on your back with your arms and legs relaxed.",
      "Close your eyes and breathe naturally.",
      "Release all tension from your body.",
      "Stay in the pose for several minutes."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Natural, effortless breathing.",
    commonMistakes: ["Fidgeting", "Falling asleep"],
    safetyTips: ["Place a bolster under your knees if you have lower back pain."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 300
  },
  {
    id: "mukonasanam",
    name: "Triangle Pose",
    sanskritName: "Mukonasanam (Trikonasana)",
    description: "A standing pose that stretches the legs, spine, and hips while improving balance.",
    benefits: ["Stretches legs and side body", "Improves balance and stability", "Opens hips and chest"],
    instructions: [
      "Stand with your feet about 3-4 feet apart.",
      "Turn your right foot out and keep your left foot slightly in.",
      "Inhale and extend your arms out to the sides.",
      "Exhale and reach your right hand toward your shin or a block.",
      "Extend your left arm upward and keep your chest open."
    ],
  difficulty: "Beginner", 
    category: "Beginner",
    breathing: "Inhale to lengthen the spine, exhale to deepen the side stretch.",
    commonMistakes: ["Collapsing the chest", "Locking the front knee", "Overreaching to the floor"],
  safetyTips: [
    "Use a block under the lower hand if you can't reach the shin or floor.",
  ],
  imageUrl: "images/Mukonasanam.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 45
  },
  {
    id: "ardha_uttanasana",
    name: "Half Forward Bend",
    sanskritName: "Ardha Uttanasana",
    description: "A transition pose that stretches the front of the torso and the hamstrings.",
    benefits: ["Stretches the front of the torso", "Strengthens the back", "Improves posture"],
    instructions: [
      "From a Standing Forward Bend, inhale and lift your torso.",
      "Keep your back flat and gaze forward.",
      "Place your hands on your shins or the floor.",
      "Lengthen your spine from the tailbone to the crown."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Inhale as you lift and lengthen.",
    commonMistakes: ["Rounding the back", "Locking the knees"],
    safetyTips: ["Keep your knees slightly bent if your hamstrings are tight."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "uttanasana",
    name: "Standing Forward Bend",
    sanskritName: "Uttanasana",
    description: "A powerful stretch for the hamstrings and the entire back of the body.",
    benefits: ["Stretches hamstrings and calves", "Calms the brain", "Relieves stress"],
    instructions: [
      "Stand with your feet hip-width apart.",
      "Exhale and fold forward from your hips.",
      "Reach for your feet or the floor.",
      "Let your head hang heavy."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Exhale as you fold forward.",
    commonMistakes: ["Folding from the waist instead of the hips", "Locking the knees"],
    safetyTips: ["Keep a slight bend in your knees if needed."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 60
  },
  {
    id: "anjaneyasana",
    name: "Low Lunge Pose",
    sanskritName: "Anjaneyasana",
    description: "A deep stretch for the hips and quadriceps.",
    benefits: ["Stretches the hip flexors", "Strengthens the legs", "Opens the chest"],
    instructions: [
      "From Downward Dog, step your right foot forward between your hands.",
      "Lower your left knee to the floor.",
      "Inhale and lift your torso, reaching your arms up.",
      "Sink your hips forward and down."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Inhale as you lift the torso and arms.",
    commonMistakes: ["Front knee moving past the ankle", "Not engaging the core"],
    safetyTips: ["Place a blanket under your back knee for comfort."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 45
  },
  {
    id: "malasana",
    name: "Garland Pose",
    sanskritName: "Malasana",
    description: "A deep squat that opens the hips and stretches the ankles.",
    benefits: ["Opens the hips", "Stretches the ankles and groin", "Tones the abdomen"],
    instructions: [
      "Squat with your feet as close together as possible.",
      "Separate your thighs slightly wider than your torso.",
      "Press your elbows against your inner knees.",
      "Bring your palms together in prayer position."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Deep, abdominal breaths.",
    commonMistakes: ["Heels lifting off the floor", "Rounding the back"],
    safetyTips: ["Sit on a block if your heels don't reach the floor."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 45
  },
  {
    id: "ananda_balasana",
    name: "Happy Baby Pose",
    sanskritName: "Ananda Balasana",
    description: "A gentle hip opener that also stretches the inner groins and back spine.",
    benefits: ["Gently stretches the inner groins", "Calms the brain", "Relieves stress and fatigue"],
    instructions: [
      "Lie on your back and exhale, bending your knees into your belly.",
      "Inhale, grip the outside of each foot with your hands.",
      "Open your knees slightly wider than your torso.",
      "Pull your knees toward the floor beside your torso."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Deep, relaxing breaths.",
    commonMistakes: ["Shoulders lifting off the floor", "Holding the breath"],
    safetyTips: ["Use a strap if you can't reach your feet."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 60
  },
  {
    id: "uttana_shishosana",
    name: "Puppy Pose",
    sanskritName: "Uttana Shishosana",
    description: "A cross between Child's Pose and Downward Dog, it stretches the spine and shoulders.",
    benefits: ["Stretches the spine and shoulders", "Calms the mind", "Relieves stress"],
    instructions: [
      "Start on all fours.",
      "Walk your hands forward and lower your chest toward the floor.",
      "Keep your hips over your knees.",
      "Rest your forehead or chin on the mat."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Breathe into the back of the heart.",
    commonMistakes: ["Hips moving forward or back", "Collapsing in the lower back"],
    safetyTips: ["Place a blanket under your knees if needed."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 60
  },
  {
    id: "paschimottanasana",
    name: "Seated Forward Bend",
    sanskritName: "Patchimotasana (Paschimottanasana)",
    description: "A deep forward bend that stretches the spine and hamstrings while calming the mind.",
    benefits: ["Stretches hamstrings and spine", "Supports digestion", "Soothes the nervous system"],
    instructions: [
      "Sit with your legs extended straight in front of you.",
      "Inhale and reach your arms up.",
      "Exhale and fold forward from your hips.",
      "Reach for your feet or shins.",
      "Keep your spine long and avoid rounding your back excessively."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Inhale to lengthen, exhale to fold deeper.",
    commonMistakes: ["Rounding the upper back", "Forcing the stretch"],
    safetyTips: ["Keep a slight bend in your knees if your hamstrings are very tight."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 60
  },
  {
    id: "baddha_konasana",
    name: "Butterfly Pose",
    sanskritName: "Baddha Konasana",
    description: "A seated pose that opens the hips and inner thighs.",
    benefits: ["Opens hips", "Stretches inner thighs", "Relieves menstrual discomfort"],
    instructions: [
      "Sit with your legs extended.",
      "Bend your knees and bring the soles of your feet together.",
      "Let your knees fall out to the sides.",
      "Hold your feet or ankles and sit tall.",
      "Gently press your knees toward the floor."
    ],
    difficulty: "Beginner",
    category: "Stretching",
    breathing: "Deep, relaxing breaths into the hips.",
    commonMistakes: ["Forcing the knees down", "Rounding the spine"],
    safetyTips: ["Place blocks under your knees for support if needed."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 60
  },
  {
    id: "virabhadrasana_1",
    name: "Warrior I",
    sanskritName: "Virabhadrasana I",
    description: "A powerful standing pose that builds strength and focus.",
    benefits: ["Strengthens legs and arms", "Opens chest and lungs", "Improves focus"],
    instructions: [
      "Start in Mountain Pose.",
      "Step your right foot back about 3-4 feet.",
      "Turn your right foot out 45 degrees.",
      "Bend your left knee so it's directly over your ankle.",
      "Reach your arms up toward the ceiling.",
      "Square your hips toward the front."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Inhale as you reach up, exhale as you ground down.",
    commonMistakes: ["Front knee moving past the ankle", "Hips not squared"],
    safetyTips: ["Keep your back heel grounded for stability."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 45
  },
  {
    id: "virabhadrasana_2",
    name: "Warrior II",
    sanskritName: "Virabhadrasana II",
    description: "A standing pose that builds stamina and stretches the hips.",
    benefits: ["Strengthens legs and ankles", "Stretches hips and groin", "Increases stamina"],
    instructions: [
      "Start in Mountain Pose.",
      "Step your feet 3-4 feet apart.",
      "Turn your right foot out 90 degrees and left foot in slightly.",
      "Bend your right knee over your ankle.",
      "Extend your arms out to the sides, parallel to the floor.",
      "Gaze over your right hand."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Steady, powerful breaths.",
    commonMistakes: ["Leaning the torso forward", "Front knee collapsing inward"],
    safetyTips: ["Keep your core engaged to support your lower back."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 45
  },
  {
    id: "virabhadrasana_3",
    name: "Warrior III",
    sanskritName: "Virabhadrasana III",
    description: "A challenging balancing pose that strengthens the legs and core.",
    benefits: ["Strengthens the legs and ankles", "Tones the abdomen", "Improves balance and posture"],
    instructions: [
      "From Warrior I, lean your torso forward.",
      "Shift your weight onto your front foot.",
      "Lift your back leg until it's parallel to the floor.",
      "Extend your arms forward or out to the sides."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Steady, focused breathing.",
    commonMistakes: ["Dropping the lifted leg", "Locking the standing knee"],
    safetyTips: ["Keep your standing knee slightly soft."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "trikonasana",
    name: "Triangle Pose",
    sanskritName: "Trikonasana",
    description: "A foundational standing pose that stretches the entire body.",
    benefits: ["Stretches legs, spine, and chest", "Improves digestion", "Relieves backache"],
    instructions: [
      "Stand with your feet 3-4 feet apart.",
      "Turn your right foot out 90 degrees.",
      "Extend your arms out to the sides.",
      "Reach your right hand toward your right shin or the floor.",
      "Extend your left arm toward the ceiling.",
      "Look up at your left hand."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Inhale to expand the chest, exhale to deepen the side stretch.",
    commonMistakes: ["Locking the front knee", "Collapsing the bottom side of the torso"],
    safetyTips: ["Use a block under your bottom hand if you can't reach the floor."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 45
  },
  {
    id: "navasana",
    name: "Boat Pose",
    sanskritName: "Navasana",
    description: "A core-strengthening pose that improves balance.",
    benefits: ["Strengthens abdominal muscles", "Improves balance", "Stimulates kidneys and intestines"],
    instructions: [
      "Sit with your knees bent and feet flat on the floor.",
      "Lean back slightly and lift your feet off the floor.",
      "Extend your legs straight (or keep knees bent for a modification).",
      "Extend your arms forward, parallel to the floor.",
      "Keep your spine long and chest lifted."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Don't hold your breath; keep it steady despite the core engagement.",
    commonMistakes: ["Rounding the back", "Holding the breath"],
    safetyTips: ["Keep your knees bent if you feel any strain in your lower back."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "viparita_virabhadrasana",
    name: "Reverse Warrior",
    sanskritName: "Viparita Virabhadrasana",
    description: "A standing pose that stretches the side body and improves balance.",
    benefits: ["Stretches the side body", "Strengthens the legs", "Improves spinal flexibility"],
    instructions: [
      "From Warrior II, reach your front arm up and back.",
      "Place your back hand on your back leg.",
      "Keep the front knee bent over the ankle.",
      "Gaze up at your raised hand."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Inhale as you reach back, expanding the side ribs.",
    commonMistakes: ["Straightening the front knee", "Collapsing into the back hand"],
    safetyTips: ["Keep your core engaged to protect your lower back."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "utthita_parsvakonasana",
    name: "Extended Side Angle",
    sanskritName: "Utthita Parsvakonasana",
    description: "A standing pose that stretches the side body and strengthens the legs.",
    benefits: ["Strengthens the legs and ankles", "Stretches the groins and spine", "Increases stamina"],
    instructions: [
      "From Warrior II, lean forward and place your front forearm on your thigh.",
      "Reach your back arm over your head, creating a straight line from heel to fingertips.",
      "Gaze up toward your top arm.",
      "Keep your front knee bent at 90 degrees."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Deep, expansive breaths into the side body.",
    commonMistakes: ["Collapsing the chest toward the floor", "Front knee moving past the ankle"],
    safetyTips: ["Use a block under your bottom hand if needed."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 45
  },
  {
    id: "ardha_pincha_mayurasana",
    name: "Dolphin Pose",
    sanskritName: "Ardha Pincha Mayurasana",
    description: "A pose that strengthens the shoulders and core while stretching the hamstrings.",
    benefits: ["Strengthens shoulders and arms", "Stretches hamstrings and calves", "Calms the brain"],
    instructions: [
      "Start on your hands and knees.",
      "Lower your forearms to the floor, shoulder-width apart.",
      "Tuck your toes and lift your hips toward the ceiling.",
      "Walk your feet toward your elbows."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Steady, rhythmic breathing.",
    commonMistakes: ["Rounding the back", "Collapsing into the shoulders"],
    safetyTips: ["Keep your elbows directly under your shoulders."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 45
  },
  {
    id: "dhanurasana",
    name: "Bow Pose",
    sanskritName: "Dhanurasana",
    description: "A backbend that stretches the entire front of the body.",
    benefits: ["Stretches the entire front of the body", "Strengthens back muscles", "Improves posture"],
    instructions: [
      "Lie on your belly with your arms by your sides.",
      "Bend your knees and reach back to grab your ankles.",
      "Inhale and lift your chest and thighs off the floor.",
      "Gaze forward and breathe deeply."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Breathe into the belly to help lift the torso.",
    commonMistakes: ["Holding the breath", "Knees splaying too wide"],
    safetyTips: ["Avoid if you have a recent back or neck injury."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "phalakasana",
    name: "Plank Pose",
    sanskritName: "Phalakasana",
    description: "A foundational core-strengthening pose.",
    benefits: ["Strengthens the core and arms", "Tones the abdomen", "Improves posture"],
    instructions: [
      "Start in Downward Dog, then shift your weight forward.",
      "Align your shoulders over your wrists.",
      "Keep your body in a straight line from head to heels.",
      "Engage your core and thighs."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Steady, controlled breathing.",
    commonMistakes: ["Hips sagging or lifting too high", "Holding the breath"],
    safetyTips: ["Keep your neck neutral, gazing slightly forward."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 60
  },
  {
    id: "vasisthasana",
    name: "Side Plank Pose",
    sanskritName: "Vasisthasana",
    description: "A balancing pose that strengthens the arms and core.",
    benefits: ["Strengthens the arms and wrists", "Tones the abdomen", "Improves balance"],
    instructions: [
      "From Plank Pose, shift your weight onto your right hand.",
      "Roll onto the outer edge of your right foot.",
      "Stack your left foot on top of your right.",
      "Extend your left arm toward the ceiling."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Focused, steady breathing.",
    commonMistakes: ["Hips sagging toward the floor", "Holding the breath"],
    safetyTips: ["Lower your bottom knee for a modification if needed."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "garudasana",
    name: "Eagle Pose",
    sanskritName: "Garudasana",
    description: "A balancing pose that stretches the shoulders and upper back.",
    benefits: ["Improves balance and focus", "Stretches shoulders and upper back", "Strengthens legs and ankles"],
    instructions: [
      "Stand in Mountain Pose, then bend your knees slightly.",
      "Wrap your right leg over your left thigh.",
      "Wrap your right arm under your left arm.",
      "Bring your palms together and lift your elbows."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Breathe into the space between the shoulder blades.",
    commonMistakes: ["Losing balance", "Holding tension in the neck"],
    safetyTips: ["Keep your gaze fixed on a steady point."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "urdhva_dhanurasana",
    name: "Wheel Pose",
    sanskritName: "Urdhva Dhanurasana",
    description: "A deep backbend that opens the entire front of the body.",
    benefits: ["Strengthens arms, legs, and spine", "Opens chest and lungs", "Increases energy"],
    instructions: [
      "Lie on your back with knees bent and feet flat.",
      "Place your hands by your ears, fingers pointing toward your shoulders.",
      "Press into your hands and feet to lift your body off the floor.",
      "Straighten your arms as much as possible."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Breathe deeply into the expanded chest.",
    commonMistakes: ["Feet turning outward", "Holding the breath"],
    safetyTips: ["Warm up your spine thoroughly before attempting."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "ustrasana",
    name: "Camel Pose",
    sanskritName: "Ustrasana",
    description: "A deep backbend that opens the entire front of the body.",
    benefits: ["Stretches the entire front of the body", "Strengthens back muscles", "Improves posture"],
    instructions: [
      "Kneel on the floor with your knees hip-width apart.",
      "Place your hands on your lower back for support.",
      "Inhale and lift your chest.",
      "Exhale and lean back, reaching for your heels.",
      "Keep your hips over your knees."
    ],
    difficulty: "Intermediate",
    category: "Back Pain Relief",
    breathing: "Breathe deeply into the chest.",
    commonMistakes: ["Crunching the lower back", "Dropping the head back too far"],
    safetyTips: ["Keep your hands on your lower back if reaching for heels is too intense."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 30
  },
  {
    id: "ardha_chandrasana",
    name: "Half Moon Pose",
    sanskritName: "Ardha Chandrasana",
    description: "A challenging balancing pose that strengthens the legs and core.",
    benefits: ["Improves balance and coordination", "Strengthens legs and ankles", "Stretches the chest"],
    instructions: [
      "Start in Triangle Pose on the right side.",
      "Place your right hand on the floor about a foot in front of your right foot.",
      "Lift your left leg parallel to the floor.",
      "Extend your left arm toward the ceiling.",
      "Turn your torso to the left."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Focus on a steady gaze (drishti) and steady breath.",
    commonMistakes: ["Dropping the lifted leg", "Not engaging the core"],
    safetyTips: ["Use a block under your bottom hand for better stability."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 30
  },
  {
    id: "bakasana",
    name: "Crow Pose",
    sanskritName: "Bakasana",
    description: "An introductory arm balance that builds upper body and core strength.",
    benefits: ["Strengthens arms and wrists", "Tones abdominal muscles", "Improves balance"],
    instructions: [
      "Squat down and place your hands on the floor, shoulder-width apart.",
      "Place your knees on the back of your upper arms.",
      "Lean forward and shift your weight into your hands.",
      "Lift one foot, then the other, off the floor.",
      "Gaze forward, not down."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Keep the breath calm to maintain focus.",
    commonMistakes: ["Looking straight down", "Not engaging the core"],
    safetyTips: ["Place a pillow in front of you in case you tip forward."],
  imageUrl: "images/Veerabadhrasana.jpg",
    duration: 20
  },
  {
    id: "sirsasana_prep",
    name: "Headstand Preparation",
    sanskritName: "Sirsasana Prep",
    description: "Builds shoulder stability and core strength for safe inversions.",
    benefits: ["Strengthens shoulders and core", "Improves balance awareness", "Prepares for full headstand"],
    instructions: [
      "Kneel and interlace your fingers, placing your forearms on the mat.",
      "Create a triangle with your elbows and keep your shoulders lifted.",
      "Tuck your toes and lift your hips into Dolphin Pose.",
      "Walk your feet closer until your hips stack over your shoulders.",
      "Hold while pressing forearms firmly into the mat."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Slow, steady breaths to keep the neck long and the core engaged.",
    commonMistakes: ["Collapsing into the shoulders", "Letting elbows splay wide"],
    safetyTips: ["Avoid if you have neck issues and keep weight in the forearms, not the head."],
  imageUrl: "images/Padmasana.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 45
  },
  {
    id: "sirsasana",
    name: "Headstand",
    sanskritName: "Sirsasana",
    description: "The 'king' of all YOGSHALA poses, an inversion that requires strength and focus.",
    benefits: ["Increases circulation to the brain", "Strengthens core and shoulders", "Calms the mind"],
    instructions: [
      "Kneel and interlace your fingers, placing your forearms on the floor.",
      "Place the crown of your head on the floor, cradled by your hands.",
      "Lift your hips and walk your feet toward your head.",
      "Slowly lift your legs toward the ceiling.",
      "Engage your core and keep your weight on your forearms."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Slow, controlled breathing is essential.",
    commonMistakes: ["Putting too much weight on the head", "Collapsing the shoulders"],
    safetyTips: ["Practice against a wall until you are confident in your balance."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 30
  },
  {
    id: "vrischikasana",
    name: "Scorpion Pose",
    sanskritName: "Vrischikasana",
    description: "An advanced inversion and backbend that requires extreme strength and flexibility.",
    benefits: ["Strengthens arms, shoulders, and back", "Improves balance", "Stretches the front of the body"],
    instructions: [
      "Start in a Forearm Stand.",
      "Bend your knees and reach your feet toward your head.",
      "Lift your chest and look forward.",
      "Keep your core engaged to protect your spine."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Focus on deep, steady breaths despite the intense backbend.",
    commonMistakes: ["Losing core engagement", "Forcing the backbend"],
    safetyTips: ["Only attempt with a spotter or against a wall if you're learning."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    duration: 15
  },
  {
    id: "pincha_mayurasana",
    name: "Forearm Stand",
    sanskritName: "Pincha Mayurasana",
    description: "A challenging inversion that builds shoulder strength and balance.",
    benefits: ["Strengthens shoulders, arms, and back", "Improves balance", "Calms the brain"],
    instructions: [
      "Start in Dolphin Pose.",
      "Gaze forward between your hands.",
      "Lift one leg, then the other, into the air.",
      "Engage your core and reach through your feet."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Steady, controlled breathing.",
    commonMistakes: ["Collapsing into the shoulders", "Arching the back too much"],
    safetyTips: ["Practice against a wall until you find your balance."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 20
  },
  {
    id: "adho_mukha_vrksasana",
    name: "Handstand",
    sanskritName: "Adho Mukha Vrksasana",
    description: "The ultimate inversion that requires significant upper body strength and balance.",
    benefits: ["Strengthens shoulders, arms, and wrists", "Improves balance", "Increases focus"],
    instructions: [
      "Start in Downward Dog with your hands a few inches from a wall.",
      "Step one foot forward and kick the other leg up.",
      "Bring both legs together and reach through your heels.",
      "Engage your core and push away from the floor."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Steady, calm breathing.",
    commonMistakes: ["Arching the back", "Looking straight down"],
    safetyTips: ["Practice with a wall or a spotter."],
  imageUrl: "images/Thadasana.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 15
  },
  {
    id: "one_handed_handstand",
    name: "One-Handed Handstand",
    sanskritName: "Eka Hasta Adho Mukha Vrksasana",
    description: "An advanced handstand variation requiring exceptional balance and body control.",
    benefits: ["Builds shoulder stability", "Enhances balance and focus", "Develops full-body control"],
    instructions: [
      "Kick up into a stable handstand near a wall or with a spotter.",
      "Shift your weight into one hand while engaging the core tightly.",
      "Float the opposite hand a few centimeters off the floor.",
      "Keep your hips stacked and legs active to maintain balance."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Soft, controlled breaths to stabilize the core and shoulders.",
    commonMistakes: ["Over-shifting the hips", "Letting the ribs flare"],
    safetyTips: ["Practice with a wall or spotter and avoid if wrists or shoulders are strained."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 10
  },
  {
    id: "astavakrasana",
    name: "Eight Angle Pose",
    sanskritName: "Astavakrasana",
    description: "A complex arm balance that requires core strength and hip flexibility.",
    benefits: ["Strengthens arms and wrists", "Tones the abdomen", "Improves balance"],
    instructions: [
      "From a seated position, hook one leg over your upper arm.",
      "Place your hands on the floor and lift your hips.",
      "Hook your other ankle over the first one.",
      "Extend your legs to the side and bend your elbows."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Keep the breath steady to maintain the balance.",
    commonMistakes: ["Not engaging the core", "Losing the leg hook"],
    safetyTips: ["Ensure your hips and hamstrings are well warmed up."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 15
  },
  {
    id: "mayurasana",
    name: "Peacock Pose",
    sanskritName: "Mayurasana",
    description: "An advanced arm balance where the body is balanced on the elbows.",
    benefits: ["Strengthens the core and arms", "Improves digestion", "Tones the abdomen"],
    instructions: [
      "Kneel and place your hands on the floor, fingers pointing back.",
      "Bring your elbows together and place them against your abdomen.",
      "Lean forward and extend your legs back.",
      "Balance your body parallel to the floor."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Steady, shallow breaths due to the pressure on the abdomen.",
    commonMistakes: ["Elbows splaying apart", "Losing core engagement"],
    safetyTips: ["Avoid if you have any abdominal issues or are pregnant."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 15
  },
  {
    id: "eka_pada_galavasana",
    name: "Flying Pigeon Pose",
    sanskritName: "Eka Pada Galavasana",
    description: "An advanced arm balance that combines hip opening and strength.",
    benefits: ["Strengthens arms and core", "Opens the hips", "Improves balance"],
    instructions: [
      "From a standing position, cross one ankle over the opposite knee.",
      "Place your hands on the floor and hook your foot around your upper arm.",
      "Lean forward and lift your back leg into the air.",
      "Extend the back leg straight."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Focused, steady breathing.",
    commonMistakes: ["Losing the foot hook", "Not leaning forward enough"],
    safetyTips: ["Warm up your hips thoroughly before attempting."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 15
  },
  {
    id: "rajakapotasana",
    name: "King Pigeon Pose",
    sanskritName: "Rajakapotasana",
    description: "A deep backbend and hip opener.",
    benefits: ["Stretches the entire front of the body", "Opens the hips", "Strengthens the back"],
    instructions: [
      "From Pigeon Pose, bend your back knee.",
      "Reach back with both hands and grab your foot.",
      "Lift your chest and reach your head toward your foot.",
      "Keep your hips squared."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Deep, expansive breaths into the chest.",
    commonMistakes: ["Crunching the lower back", "Hips not squared"],
    safetyTips: ["Use a strap if you can't reach your foot."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "padmasana",
    name: "Lotus Pose",
    sanskritName: "Padmasana",
    description: "A seated meditation pose that promotes focus, calm, and hip flexibility.",
    benefits: ["Promotes concentration and calm", "Improves hip flexibility", "Supports upright posture"],
    instructions: [
      "Sit on the floor and place one foot on the opposite thigh.",
      "Place the other foot on the first thigh.",
      "Keep your spine straight and hands on your knees.",
      "Sit tall and breathe deeply."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Deep, meditative breathing.",
    commonMistakes: ["Forcing the knees", "Slouching"],
    safetyTips: ["Avoid if you have any knee or ankle injuries."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 300
  },
  {
    id: "baddha_padmasana",
    name: "Bound Lotus Pose",
    sanskritName: "Baddha Padmasana",
    description: "An advanced variation of Lotus where the feet are held from behind.",
    benefits: ["Deeply opens the shoulders", "Improves digestion", "Calms the mind"],
    instructions: [
      "Sit in Lotus Pose.",
      "Reach your arms behind your back.",
      "Cross your arms and grab your big toes.",
      "Sit tall and breathe deeply."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Steady, calm breathing.",
    commonMistakes: ["Straining the shoulders", "Losing the Lotus bind"],
    safetyTips: ["Only attempt if you are very comfortable in Lotus Pose."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 60
  },
  {
    id: "parivrtta_surya_yantrasana",
    name: "Compass Pose",
    sanskritName: "Parivrtta Surya Yantrasana",
    description: "A seated pose that requires extreme hamstring and shoulder flexibility.",
    benefits: ["Stretches the hamstrings and side body", "Opens the shoulders", "Improves spinal flexibility"],
    instructions: [
      "Sit with one leg bent and the other leg hooked over your shoulder.",
      "Grab the foot of the hooked leg with the opposite hand.",
      "Straighten the leg and look under your arm.",
      "Keep your spine long."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Breathe into the side body and hamstrings.",
    commonMistakes: ["Rounding the back", "Forcing the leg straight"],
    safetyTips: ["Warm up your hamstrings and shoulders thoroughly."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "maksikanagasana",
    name: "Grasshopper Pose",
    sanskritName: "Maksikanagasana",
    description: "A complex arm balance that involves a twist and hip opening.",
    benefits: ["Strengthens arms and core", "Improves balance", "Deeply twists the spine"],
    instructions: [
      "From a standing position, twist and place your hands on the floor.",
      "Place one foot on the back of your upper arm.",
      "Lean forward and lift your back leg into the air.",
      "Extend the back leg straight."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Keep the breath steady to support the twist.",
    commonMistakes: ["Losing the foot placement", "Not leaning forward enough"],
    safetyTips: ["Ensure your spine and hips are well warmed up."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 15
  },
  {
    id: "parsva_bakasana",
    name: "Side Crow Pose",
    sanskritName: "Parsva Bakasana",
    description: "An advanced arm balance that involves a deep spinal twist.",
    benefits: ["Strengthens arms and wrists", "Tones the abdomen", "Improves balance"],
    instructions: [
      "Squat and twist your torso to one side.",
      "Place your hands on the floor and rest your outer thigh on your upper arm.",
      "Lean forward and lift your feet off the floor.",
      "Keep your legs together."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Steady, calm breathing.",
    commonMistakes: ["Not twisting deeply enough", "Looking straight down"],
    safetyTips: ["Warm up your spine with twists before attempting."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 15
  },
  {
    id: "eka_pada_rajakapotasana",
    name: "One-Legged King Pigeon Pose",
    sanskritName: "Eka Pada Rajakapotasana",
    description: "A deep backbend and hip opener that requires significant flexibility.",
    benefits: ["Stretches the hip flexors and groins", "Opens the chest and shoulders", "Strengthens the back"],
    instructions: [
      "From Pigeon Pose, bend your back knee and reach back with one hand.",
      "Hook your foot in the crook of your elbow.",
      "Reach your other arm over your head and clasp your hands.",
      "Lift your chest and look up."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Deep, expansive breaths into the chest.",
    commonMistakes: ["Crunching the lower back", "Losing balance"],
    safetyTips: ["Use a strap if you can't clasp your hands."],
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=800",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "parvatasana",
    name: "Seated Mountain Pose",
    sanskritName: "Paruvadhasanam (Parvatasana)",
    description: "A seated stretch that lengthens the spine and opens the shoulders.",
    benefits: ["Strengthens shoulders and upper back", "Lengthens the spine", "Improves seated posture"],
    instructions: [
      "Sit in a comfortable cross-legged position.",
      "Interlace your fingers and turn your palms upward.",
      "Inhale and lift your arms overhead, keeping shoulders relaxed.",
      "Lengthen the spine and sit tall.",
      "Hold for a few breaths, then release."
    ],
    difficulty: "Beginner",
    category: "Beginner",
    breathing: "Inhale to lift and lengthen, exhale to soften the shoulders.",
    commonMistakes: ["Shrugging the shoulders", "Arching the lower back", "Holding the breath"],
    safetyTips: ["Sit on a folded blanket if your hips feel tight."],
  imageUrl: "images/Paruvadhasanam.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 45
  },
  {
    id: "ardha_matsyendrasana",
    name: "Half Spinal Twist",
    sanskritName: "Arthamatseyandrasana (Ardha Matsyendrasana)",
    description: "A seated twist that builds spinal mobility and stimulates digestion.",
    benefits: ["Improves spinal flexibility", "Aids digestion", "Releases back tension"],
    instructions: [
      "Sit with legs extended, then bend your right knee and place the foot outside your left thigh.",
      "Bend your left knee and tuck the foot near your right hip or keep it extended.",
      "Inhale to lengthen the spine.",
      "Exhale and twist to the right, placing your left elbow outside your right knee.",
      "Gaze over the right shoulder and breathe steadily."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Inhale to lengthen, exhale to deepen the twist.",
    commonMistakes: ["Rounding the back", "Forcing the twist", "Collapsing the chest"],
    safetyTips: ["Keep the twist gentle if you have lower-back issues."],
  imageUrl: "images/Arthamatseyandrasana.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 45
  },
  {
    id: "matsyasana",
    name: "Fish Pose",
    sanskritName: "Machasanam (Matsyasana)",
    description: "A chest-opening backbend that expands the ribcage and throat.",
    benefits: ["Opens chest and shoulders", "Improves breathing capacity", "Stretches the neck and upper back"],
    instructions: [
      "Lie on your back with legs extended and arms by your sides.",
      "Slide your hands under your hips, palms down.",
      "Inhale and lift your chest, arching the upper back.",
      "Lower the crown of your head lightly toward the mat.",
      "Keep weight in the forearms and breathe evenly."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Slow, expansive breaths into the chest.",
    commonMistakes: ["Dumping weight into the neck", "Overarching the lower back"],
    safetyTips: ["Keep most weight in the elbows and avoid if you have a neck injury."],
  imageUrl: "images/Machasanam.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 40
  },
  {
    id: "salabhasana",
    name: "Locust Pose",
    sanskritName: "Salabasana (Salabhasana)",
    description: "A strengthening backbend that builds lower-back endurance and posture.",
    benefits: ["Strengthens lower back and glutes", "Improves posture", "Activates hamstrings"],
    instructions: [
      "Lie on your belly with arms alongside your body.",
      "Inhale and lift your chest, arms, and legs off the floor.",
      "Keep your gaze forward and neck long.",
      "Engage your glutes and lengthen through the toes.",
      "Hold for a few breaths, then release."
    ],
    difficulty: "Intermediate",
    category: "Intermediate",
    breathing: "Inhale to lift, exhale to stabilize.",
    commonMistakes: ["Overarching the lower back", "Shrugging the shoulders"],
    safetyTips: ["Avoid if you have acute lower-back pain."],
  imageUrl: "images/Salabasana.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "sarvangasana",
    name: "Shoulder Stand",
    sanskritName: "Sarvangasanam (Sarvangasana)",
    description: "An inversion that encourages circulation and steadies the mind.",
    benefits: ["Improves circulation", "Supports thyroid health", "Calms the nervous system"],
    instructions: [
      "Lie on your back with arms by your sides.",
      "Lift your legs and hips, supporting your back with your hands.",
      "Stack hips over shoulders and keep legs straight.",
      "Press into the shoulders and keep the neck long.",
      "Hold with slow breaths, then lower with control."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Slow, steady breaths through the nose.",
    commonMistakes: ["Turning the head", "Weight on the neck instead of shoulders"],
    safetyTips: ["Use a folded blanket under shoulders and avoid if you have neck issues."],
  imageUrl: "images/Sarvangasanam.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "ustrasana",
    name: "Camel Pose",
    sanskritName: "Ustrasanam (Ustrasana)",
    description: "A deep backbend that opens the chest and stretches the front body.",
    benefits: ["Opens chest and hip flexors", "Strengthens the spine", "Improves flexibility"],
    instructions: [
      "Kneel with knees hip-width apart and toes tucked.",
      "Place hands on your lower back and lift the chest.",
      "Reach back to hold the heels one at a time.",
      "Press hips forward and keep the neck long.",
      "Breathe steadily, then return slowly."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Inhale to lift the chest, exhale to deepen the backbend.",
    commonMistakes: ["Compressing the lower back", "Dropping the head too far back"],
    safetyTips: ["Support the lower back with hands if reaching the heels isn't comfortable."],
  imageUrl: "images/Ustrasanam.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "veerabadhrasana",
    name: "Warrior Pose",
    sanskritName: "Veerabadhrasana (Virabhadrasana)",
    description: "A powerful standing posture that builds strength, stability, and focus.",
    benefits: ["Strengthens legs and hips", "Improves stability", "Builds stamina"],
    instructions: [
      "Stand with feet wide and turn the front foot out.",
      "Bend the front knee over the ankle.",
      "Square the hips and extend your arms.",
      "Lift through the chest and engage the core.",
      "Hold for a few breaths, then switch sides."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Inhale to lift, exhale to ground through the feet.",
    commonMistakes: ["Front knee collapsing inward", "Leaning forward too much"],
    safetyTips: ["Keep the front knee aligned over the ankle."],
  imageUrl: "images/Veerabadhrasana.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 40
  },
  {
    id: "yerasanam",
    name: "Plough Pose",
    sanskritName: "Yerasanam (Halasana)",
    description: "An advanced inversion that challenges balance and concentration.",
    benefits: ["Improves balance and focus", "Increases circulation", "Builds shoulder strength"],
    instructions: [
      "Interlace fingers and place forearms on the mat.",
      "Place the crown of your head lightly on the floor.",
      "Lift your hips and walk feet toward your head.",
      "Engage the core and lift the legs upward.",
      "Hold with steady breaths, then lower slowly."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Slow, controlled breathing.",
    commonMistakes: ["Putting too much weight on the head", "Letting elbows splay out"],
    safetyTips: ["Practice against a wall and avoid if you have neck issues."],
  imageUrl: "images/Yerasanam.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 30
  },
  {
    id: "mulagal_thalai_asanam",
    name: "Mulagal Thalai Asanam",
    sanskritName: "Mulagal Thalai Asanam",
    description: "A challenging head/neck balancing posture that requires advanced strength and control.",
    benefits: ["Builds neck and core strength", "Improves body control", "Enhances concentration"],
    instructions: [
      "Start from a stable kneeling position with forearms grounded.",
      "Create a firm base and place the head gently in position.",
      "Engage the core and lift the hips over the shoulders.",
      "Balance with controlled breaths and a long neck.",
      "Exit slowly and rest in Child's Pose."
    ],
    difficulty: "Advanced",
    category: "Advanced",
    breathing: "Calm, steady breaths to maintain balance.",
    commonMistakes: ["Rushing the lift", "Collapsing the shoulders", "Holding the breath"],
    safetyTips: ["Only attempt with supervision and avoid if you have neck issues."],
  imageUrl: "images/Mulagal thalai asanam.jpg",
    videoUrl: DEFAULT_POSE_VIDEO,
    duration: 20
  }
];

const POSE_IMAGE_OVERRIDES: Record<string, string> = {
  tadasana: "images/Thadasana.jpg",
  savasana: "images/Savasanam.jpg",
  mukonasanam: "images/Mukonasanam.jpg",
  parvatasana: "images/Paruvadhasanam.jpg",
  padmasana: "images/Padmasana.jpg",
  navasana: "images/Machasanam.jpg",
  dhanurasana: "images/Dhanurasana.jpg",
  paschimottanasana: "images/Patchimotasana.jpg",
  ardha_matsyendrasana: "images/Arthamatseyandrasana.jpg",
  matsyasana: "images/Machasanam.jpg",
  salabhasana: "images/Salabasana.jpg",
  sirsasana_prep: "images/Sarvangasanam.jpg",
  sirsasana: "images/Yerasanam.jpg",
  vrischikasana: "images/Paruvadhasanam.jpg",
  pincha_mayurasana: "images/Salabasana.jpg",
  urdhva_dhanurasana: "images/Dhanurasana.jpg",
  rajakapotasana: "images/Paruvadhasanam.jpg",
  sarvangasana: "images/Sarvangasanam.jpg",
  ustrasana: "images/Ustrasanam.jpg",
  veerabadhrasana: "images/Veerabadhrasana.jpg",
  yerasanam: "images/Yerasanam.jpg",
  mulagal_thalai_asanam: "images/Mulagal thalai asanam.jpg",
};

YOGSHALA_POSES.forEach((pose) => {
  const override = POSE_IMAGE_OVERRIDES[pose.id];
  if (override) {
    pose.imageUrl = override;
  }
});

export const MOTIVATIONAL_QUOTES = [
  "YOGSHALA is the journey of the self, through the self, to the self.",
  "The very heart of YOGSHALA practice is ‘abyhasa’ – steady effort in the direction you want to go.",
  "YOGSHALA is not about touching your toes, it's about what you learn on the way down.",
  "Your body exists in the past and your mind exists in the future. In YOGSHALA, they come together in the present.",
  "YOGSHALA does not just change the way we see things, it transforms the person who sees."
];
